Repository wecode-bootcamp-korea/35-1st-magazine-K-backend, pull requests merged in 2022-07, with the labels that each got.

#1 [김동규] Project : magazine k 초기 세팅
  .gitignore
  magazinek/__init__.py
  magazinek/asgi.py
  magazinek/settings.py
  magazinek/urls.py
  magazinek/wsgi.py
  manage.py
  requirements.txt
Labels: 완료

#2 [35기 김동규] Magazine K 데이터베이스 모델링
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  magazinek/settings.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_alter_orderitem_order_quantity.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/0002_alter_product_pages.py
  products/migrations/0003_subcategoryproduct_remove_product_sub_category_and_more.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/urls.py
  products/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: 멘토 리뷰 요청

#3 [35기 김동규] 데이터베이스 데이터 타입 및 속성 수정
  .gitignore
  orders/migrations/0001_initial.py
  orders/migrations/0002_alter_orderitem_order_quantity.py
  orders/models.py
  products/migrations/0001_initial.py
  products/migrations/0002_alter_product_pages.py
  products/migrations/0002_rename_sub_category_categoryproduct_category.py
  products/migrations/0003_subcategoryproduct_remove_product_sub_category_and_more.py
  products/models.py
  users/migrations/0001_initial.py
  users/models.py
Labels: 멘토 리뷰 요청

#4 [35기 황유정] Add : users app - view 클래스 작성
  .gitignore
  core/utils/login_decorator.py
  core/utils/validatior.py
  magazinek/settings.py
  magazinek/urls.py
  products/migrations/0004_alter_product_date.py
  requirements.txt
  users/migrations/0002_alter_user_point.py
  users/models.py
  users/urls.py
  users/views.py
Labels: 멘토 리뷰 요청

#8 [35기 황유정] login decorator 코드 오류 수정
  .gitignore
  core/utils/login_decorator.py
Labels: 멘토 리뷰 요청

#9 [35기 김동규] 데이터베이스 모델링 변경사항 적용
  .gitignore
  orders/migrations/0001_initial.py
  orders/models.py
  products/migrations/0001_initial.py
  products/migrations/0002_rename_sub_category_categoryproduct_category.py
  products/models.py
  products/urls.py
  users/migrations/0001_initial.py
Labels: 멘토 리뷰 요청

#7 [35기 황유정] 제품 디테일 페이지 view 구현
  .gitignore
  magazinek/urls.py
  products/migrations/0004_alter_product_date.py
  products/urls.py
  products/views.py
Labels: 멘토 리뷰 요청

#5 [35기 김동규] 상품 메인 리스트 페이지 로직
  magazinek/urls.py
  products/urls.py
  products/views.py
  users/migrations/0002_alter_user_point.py
Labels: 멘토 리뷰 요청

#11 [35기 황유정] Comments app 모델링
  .gitignore
  comments/__init__.py
  comments/admin.py
  comments/apps.py
  comments/migrations/0001_initial.py
  comments/migrations/0002_alter_comment_content.py
  comments/migrations/__init__.py
  comments/models.py
  comments/tests.py
  comments/views.py
  magazinek/settings.py
  products/urls.py
Labels: 멘토 리뷰 요청

#13 [35기 황유정] login decorator 오탈자 수정
  users/views.py
Labels: 멘토 리뷰 요청

#15 [35기 황유정] app 기능 명칭 변경 리모델링
  comments/migrations/0002_alter_comment_content.py
  magazinek/settings.py
  reviews/__init__.py
  reviews/admin.py
  reviews/apps.py
  reviews/migrations/0001_initial.py
  reviews/migrations/__init__.py
  reviews/models.py
  reviews/tests.py
  reviews/views.py
Labels: 멘토 리뷰 요청

#17 [35기 황유정] reviews get 기능구현
  magazinek/urls.py
  reviews/urls.py
  reviews/views.py
Labels: 멘토 리뷰 요청

#18 [35기 황유정] reviews post 기능 구현
  magazinek/urls.py
  reviews/views.py
Labels: 멘토 리뷰 요청

#10 [35기 김동규] 장바구니 및 구매
  core/utils/login_decorator.py
  magazinek/settings.py
  magazinek/urls.py
  orders/urls.py
  orders/views.py
  products/urls.py
  reviews/views.py
  users/views.py
Labels: 멘토 리뷰 요청

#20 [35기 김동규] 데이터 베이스 모델링 변경사항 적용
  orders/migrations/0002_remove_orderitem_order_price.py
  orders/models.py
Labels: 완료

#19 [35기 황유정] reviews delete 기능 구현
  magazinek/settings.py
  magazinek/urls.py
  reviews/urls.py
  reviews/views.py
Labels: 멘토 리뷰 요청

#24 [35기 김동규] 기타 수정사항 관련
  orders/views.py
  users/models.py
  users/views.py
Labels: 수정 요청
